-- Generated by `pnpm registry:sync` from the module registry (src/modules/*/module.ts — TECH-SPEC §2.3, V123).
-- Do not edit: change a module.ts and sync again. Pages, capabilities and setting definitions become the
-- registry's; roles, their starting levels and capabilities, and setting defaults are written only where none
-- exist, so what an admin has changed in the browser stays. Forward-only (V103).

select audit.begin('system', 'registry.synced');

-- the five roles (seeded once; renamed in the browser)
insert into core.role (key, name_en, name_ar, sort, is_admin) values
  ('admin', 'Admin', 'مسؤول النظام', 10, true),
  ('head', 'Head of department', 'رئيس القسم', 20, false),
  ('manager', 'Manager', 'مدير', 30, false),
  ('member', 'Team member', 'عضو الفريق', 40, false),
  ('viewer', 'Viewer', 'مشاهد', 50, false)
on conflict (key) do nothing;

-- pages
insert into core.page (key, module, route, nav_group, nav_order, levels_allowed, active) values
  ('activity', 'settings', '/settings/activity', 'settings', 80, '{none,view,own,full}'::core.level[], true),
  ('appraisal', 'appraisal', '/appraisal', 'main', 100, '{none,view,own,full}'::core.level[], true),
  ('finance', 'finance', '/finance', 'main', 70, '{none,view,own,full}'::core.level[], true),
  ('kpis', 'perf', '/kpis', 'main', 80, '{none,view,own,full}'::core.level[], true),
  ('my_day', 'my_day', '/my-day', 'main', 10, '{none,view,own,full}'::core.level[], true),
  ('overview', 'overview', '/overview', 'main', 20, '{none,view,own,full}'::core.level[], true),
  ('partners', 'partners', '/partners', 'main', 30, '{none,view,own,full}'::core.level[], true),
  ('pipeline', 'pipeline', '/pipeline', 'main', 40, '{none,view,own,full}'::core.level[], true),
  ('projects', 'projects', '/projects', 'main', 50, '{none,view,own,full}'::core.level[], true),
  ('reports', 'reports', '/reports', 'main', 90, '{none,view,own,full}'::core.level[], true),
  ('settings.app', 'settings', '/settings/app', 'settings', 70, '{none,full}'::core.level[], true),
  ('settings.finance', 'finance', '/settings/finance', 'settings', 50, '{none,full}'::core.level[], true),
  ('settings.org', 'org', '/settings/org', 'settings', 20, '{none,full}'::core.level[], true),
  ('settings.partners', 'partners', '/settings/partners', 'settings', 30, '{none,full}'::core.level[], true),
  ('settings.performance', 'perf', '/settings/performance', 'settings', 40, '{none,full}'::core.level[], true),
  ('settings.profile', 'settings', '/settings/profile', 'settings', 10, '{own}'::core.level[], true),
  ('settings.work', 'tasks', '/settings/work', 'settings', 60, '{none,full}'::core.level[], true),
  ('tasks', 'tasks', '/tasks', 'main', 60, '{none,view,own,full}'::core.level[], true)
on conflict (key) do update set module = excluded.module, route = excluded.route, nav_group = excluded.nav_group,
  nav_order = excluded.nav_order, levels_allowed = excluded.levels_allowed, active = true;
update core.page set active = false where active and key not in ('activity', 'appraisal', 'finance', 'kpis', 'my_day', 'overview', 'partners', 'pipeline', 'projects', 'reports', 'settings.app', 'settings.finance', 'settings.org', 'settings.partners', 'settings.performance', 'settings.profile', 'settings.work', 'tasks');

-- capabilities
insert into core.capability (key, page_key, active) values
  ('finance.credit', 'finance', true),
  ('finance.credit_control', 'partners', true),
  ('finance.import', 'finance', true),
  ('org.sign_out', 'settings.org', true),
  ('partners.assign', 'partners', true),
  ('partners.identify', 'partners', true),
  ('partners.merge', 'partners', true),
  ('tasks.assign', 'tasks', true)
on conflict (key) do update set page_key = excluded.page_key, active = true;
update core.capability set active = false where active and key not in ('finance.credit', 'finance.credit_control', 'finance.import', 'org.sign_out', 'partners.assign', 'partners.identify', 'partners.merge', 'tasks.assign');

-- setting definitions
insert into core.setting_def (key, group_page, schema, default_value, effective_dated, label_key, active) values
  ('app.arabic_enabled', 'settings.app', '{"$schema":"https://json-schema.org/draft/2020-12/schema","type":"boolean"}'::jsonb, 'false'::jsonb, false, 'setting.app.arabic_enabled', true),
  ('app.default_density', 'settings.app', '{"$schema":"https://json-schema.org/draft/2020-12/schema","type":"string","enum":["comfortable","compact"]}'::jsonb, '"comfortable"'::jsonb, false, 'setting.app.default_density', true),
  ('app.default_theme', 'settings.app', '{"$schema":"https://json-schema.org/draft/2020-12/schema","type":"string","enum":["light","dark","colorful","direct"]}'::jsonb, '"direct"'::jsonb, false, 'setting.app.default_theme', true),
  ('app.export_formats', 'settings.app', '{"$schema":"https://json-schema.org/draft/2020-12/schema","minItems":1,"type":"array","items":{"type":"string","enum":["csv","xlsx"]}}'::jsonb, '["csv","xlsx"]'::jsonb, false, 'setting.app.export_formats', true),
  ('audit.recently_deleted_days', 'settings.app', '{"$schema":"https://json-schema.org/draft/2020-12/schema","type":"integer","minimum":1,"maximum":365}'::jsonb, '30'::jsonb, false, 'setting.audit.recently_deleted_days', true),
  ('audit.undo_window_hours', 'settings.app', '{"$schema":"https://json-schema.org/draft/2020-12/schema","type":"integer","minimum":1,"maximum":168}'::jsonb, '24'::jsonb, false, 'setting.audit.undo_window_hours', true),
  ('auth.device_idle_days', 'settings.org', '{"$schema":"https://json-schema.org/draft/2020-12/schema","type":"integer","minimum":1,"maximum":365}'::jsonb, '30'::jsonb, false, 'setting.auth.device_idle_days', true),
  ('files.max_mb', 'settings.app', '{"$schema":"https://json-schema.org/draft/2020-12/schema","type":"integer","minimum":1,"maximum":50}'::jsonb, '20'::jsonb, false, 'setting.files.max_mb', true),
  ('notify.kinds_enabled', 'settings.app', '{"$schema":"https://json-schema.org/draft/2020-12/schema","type":"array","items":{"type":"string","enum":["assigned","helper_added","mentioned","changed_by_other","followed_change","decision_needed","report_issued","report_for_review","appraisal_step","import_done","alert_contract_expiring","alert_kpi_behind","alert_invoice_unpaid","alert_kpi_checkin"]}}'::jsonb, '["assigned","helper_added","mentioned","changed_by_other","followed_change","decision_needed","report_issued","report_for_review","appraisal_step","import_done","alert_contract_expiring","alert_kpi_behind","alert_invoice_unpaid","alert_kpi_checkin"]'::jsonb, false, 'setting.notify.kinds_enabled', true),
  ('partner.id_format', 'settings.partners', '{"$schema":"https://json-schema.org/draft/2020-12/schema","type":"object","properties":{"prefix":{"type":"string","pattern":"^[A-Z][A-Z0-9-]*$"},"width":{"type":"integer","minimum":3,"maximum":8}},"required":["prefix","width"],"additionalProperties":false}'::jsonb, '{"prefix":"DK-P","width":4}'::jsonb, false, 'setting.partner.id_format', true),
  ('partner.name_stop_words', 'settings.partners', '{"$schema":"https://json-schema.org/draft/2020-12/schema","type":"array","items":{"type":"string","minLength":1}}'::jsonb, '["شركة","مؤسسة","company","co","corp","corporation","ltd","limited","llc","inc","est"]'::jsonb, false, 'setting.partner.name_stop_words', true),
  ('partner.one_code_per_partner', 'settings.partners', '{"$schema":"https://json-schema.org/draft/2020-12/schema","type":"boolean"}'::jsonb, 'true'::jsonb, false, 'setting.partner.one_code_per_partner', true),
  ('work.meeting_note_on_time_days', 'settings.work', '{"$schema":"https://json-schema.org/draft/2020-12/schema","type":"integer","minimum":0,"maximum":14}'::jsonb, '1'::jsonb, true, 'setting.work.meeting_note_on_time_days', true),
  ('work.no_update_days', 'settings.work', '{"$schema":"https://json-schema.org/draft/2020-12/schema","type":"integer","minimum":1,"maximum":60}'::jsonb, '7'::jsonb, true, 'setting.work.no_update_days', true),
  ('work.pipeline_weekly_target', 'settings.work', '{"$schema":"https://json-schema.org/draft/2020-12/schema","type":"integer","minimum":0,"maximum":100}'::jsonb, '1'::jsonb, true, 'setting.work.pipeline_weekly_target', true),
  ('work.reminder_days_before_due', 'settings.work', '{"$schema":"https://json-schema.org/draft/2020-12/schema","type":"integer","minimum":0,"maximum":30}'::jsonb, '1'::jsonb, true, 'setting.work.reminder_days_before_due', true),
  ('work.week_starts_on', 'settings.work', '{"$schema":"https://json-schema.org/draft/2020-12/schema","type":"string","enum":["saturday","sunday","monday"]}'::jsonb, '"sunday"'::jsonb, true, 'setting.work.week_starts_on', true)
on conflict (key) do update set group_page = excluded.group_page, schema = excluded.schema,
  default_value = excluded.default_value, effective_dated = excluded.effective_dated,
  label_key = excluded.label_key, active = true;
update core.setting_def set active = false where active and key not in ('app.arabic_enabled', 'app.default_density', 'app.default_theme', 'app.export_formats', 'audit.recently_deleted_days', 'audit.undo_window_hours', 'auth.device_idle_days', 'files.max_mb', 'notify.kinds_enabled', 'partner.id_format', 'partner.name_stop_words', 'partner.one_code_per_partner', 'work.meeting_note_on_time_days', 'work.no_update_days', 'work.pipeline_weekly_target', 'work.reminder_days_before_due', 'work.week_starts_on');

-- entities: the tables whose records are logged, undone and followed (V127)
insert into core.entity (key, table_name, page_key, owners, is_list, private, visible, active) values
  ('account_manager', 'partner.account_manager', 'partners', 'partner.account_manager_owners', false, false, null, true),
  ('call_outcome', 'partner.call_outcome', 'settings.partners', null, true, false, null, true),
  ('campaign_code', 'partner.campaign_code', 'partners', 'owner_id', false, false, null, true),
  ('capability', 'core.capability', 'settings.org', null, false, false, null, true),
  ('code_terms', 'partner.code_terms', 'partners', null, false, false, null, true),
  ('contact', 'partner.contact', 'partners', 'partner.contact_owners', false, false, null, true),
  ('contract_term', 'partner.term', 'settings.partners', null, true, false, null, true),
  ('credit_limit', 'partner.credit_limit', 'partners', 'partner.credit_limit_owners', false, false, null, true),
  ('department', 'core.department', 'settings.org', 'head_person_id', false, false, null, true),
  ('entity', 'core.entity', 'settings.org', null, false, false, null, true),
  ('identifier', 'partner.identifier', 'partners', 'partner.identifier_owners', false, false, null, true),
  ('identifier_block', 'partner.identifier_block', 'settings.partners', null, false, false, null, true),
  ('individual_name', 'partner.individual_name', 'partners', null, false, false, null, true),
  ('page', 'core.page', 'settings.org', null, false, false, null, true),
  ('partner', 'partner.partner', 'partners', 'partner.partner_owners', false, false, null, true),
  ('partner_category', 'partner.category', 'settings.partners', null, true, false, null, true),
  ('partner_merge', 'partner.merge', 'partners', null, false, false, null, true),
  ('partner_role', 'partner.partner_role', 'partners', 'partner.partner_role_owners', false, false, null, true),
  ('partner_role_def', 'partner.role', 'settings.partners', null, true, false, null, true),
  ('partner_status', 'partner.status_change', 'partners', 'partner.status_change_owners', false, false, null, true),
  ('partner_tier', 'partner.tier', 'settings.partners', null, true, false, null, true),
  ('person', 'core.person', 'settings.org', 'id', false, false, null, true),
  ('person_auth', 'core.person_auth', 'settings.org', 'person_id', false, false, null, true),
  ('person_capability', 'core.person_capability', 'settings.org', 'person_id', false, false, null, true),
  ('person_department', 'core.person_department', 'settings.org', 'person_id', false, false, null, true),
  ('person_email', 'core.person_email', 'settings.org', 'person_id', false, false, null, true),
  ('person_level', 'core.person_page_level', 'settings.org', 'person_id', false, false, null, true),
  ('person_team', 'core.person_team_assist', 'settings.org', 'person_id', false, false, null, true),
  ('priority', 'work.priority', 'settings.work', null, true, false, null, true),
  ('profile', 'core.person_profile', 'settings.profile', 'person_id', false, false, null, true),
  ('role', 'core.role', 'settings.org', null, false, false, null, true),
  ('role_capability', 'core.role_capability', 'settings.org', null, false, false, null, true),
  ('role_field', 'partner.role_field', 'settings.partners', null, false, false, null, true),
  ('role_level', 'core.role_page_level', 'settings.org', null, false, false, null, true),
  ('saved_view', 'core.saved_view', null, 'owner_id', false, false, null, true),
  ('segment', 'partner.segment', 'settings.partners', null, true, false, null, true),
  ('setting', 'core.setting', 'settings.app', null, false, false, null, true),
  ('setting_def', 'core.setting_def', 'settings.app', null, false, false, null, true),
  ('status_reason', 'partner.status_reason', 'settings.partners', null, true, false, null, true),
  ('team', 'core.team', 'settings.org', 'lead_person_id', false, false, null, true),
  ('wording', 'core.wording', 'settings.app', null, false, false, null, true)
on conflict (key) do update set table_name = excluded.table_name, page_key = excluded.page_key,
  owners = excluded.owners, is_list = excluded.is_list, private = excluded.private, visible = excluded.visible,
  active = true;
update core.entity set active = false where active and key not in ('account_manager', 'call_outcome', 'campaign_code', 'capability', 'code_terms', 'contact', 'contract_term', 'credit_limit', 'department', 'entity', 'identifier', 'identifier_block', 'individual_name', 'page', 'partner', 'partner_category', 'partner_merge', 'partner_role', 'partner_role_def', 'partner_status', 'partner_tier', 'person', 'person_auth', 'person_capability', 'person_department', 'person_email', 'person_level', 'person_team', 'priority', 'profile', 'role', 'role_capability', 'role_field', 'role_level', 'saved_view', 'segment', 'setting', 'setting_def', 'status_reason', 'team', 'wording');

-- each role's starting level on each page, where it has none
insert into core.role_page_level (role_id, page_key, level)
select r.id, v.page_key, v.level::core.level
from (values
  ('admin', 'activity', 'full'),
  ('admin', 'appraisal', 'full'),
  ('admin', 'finance', 'full'),
  ('admin', 'kpis', 'full'),
  ('admin', 'my_day', 'full'),
  ('admin', 'overview', 'full'),
  ('admin', 'partners', 'full'),
  ('admin', 'pipeline', 'full'),
  ('admin', 'projects', 'full'),
  ('admin', 'reports', 'full'),
  ('admin', 'settings.app', 'full'),
  ('admin', 'settings.finance', 'full'),
  ('admin', 'settings.org', 'full'),
  ('admin', 'settings.partners', 'full'),
  ('admin', 'settings.performance', 'full'),
  ('admin', 'settings.profile', 'own'),
  ('admin', 'settings.work', 'full'),
  ('admin', 'tasks', 'full'),
  ('head', 'activity', 'view'),
  ('head', 'appraisal', 'own'),
  ('head', 'finance', 'full'),
  ('head', 'kpis', 'full'),
  ('head', 'my_day', 'full'),
  ('head', 'overview', 'full'),
  ('head', 'partners', 'full'),
  ('head', 'pipeline', 'full'),
  ('head', 'projects', 'full'),
  ('head', 'reports', 'full'),
  ('head', 'settings.app', 'none'),
  ('head', 'settings.finance', 'none'),
  ('head', 'settings.org', 'none'),
  ('head', 'settings.partners', 'none'),
  ('head', 'settings.performance', 'none'),
  ('head', 'settings.profile', 'own'),
  ('head', 'settings.work', 'none'),
  ('head', 'tasks', 'full'),
  ('manager', 'activity', 'view'),
  ('manager', 'appraisal', 'own'),
  ('manager', 'finance', 'full'),
  ('manager', 'kpis', 'full'),
  ('manager', 'my_day', 'full'),
  ('manager', 'overview', 'view'),
  ('manager', 'partners', 'full'),
  ('manager', 'pipeline', 'full'),
  ('manager', 'projects', 'full'),
  ('manager', 'reports', 'view'),
  ('manager', 'settings.app', 'none'),
  ('manager', 'settings.finance', 'none'),
  ('manager', 'settings.org', 'none'),
  ('manager', 'settings.partners', 'none'),
  ('manager', 'settings.performance', 'none'),
  ('manager', 'settings.profile', 'own'),
  ('manager', 'settings.work', 'none'),
  ('manager', 'tasks', 'full'),
  ('member', 'activity', 'none'),
  ('member', 'appraisal', 'own'),
  ('member', 'finance', 'own'),
  ('member', 'kpis', 'own'),
  ('member', 'my_day', 'own'),
  ('member', 'overview', 'none'),
  ('member', 'partners', 'full'),
  ('member', 'pipeline', 'own'),
  ('member', 'projects', 'own'),
  ('member', 'reports', 'view'),
  ('member', 'settings.app', 'none'),
  ('member', 'settings.finance', 'none'),
  ('member', 'settings.org', 'none'),
  ('member', 'settings.partners', 'none'),
  ('member', 'settings.performance', 'none'),
  ('member', 'settings.profile', 'own'),
  ('member', 'settings.work', 'none'),
  ('member', 'tasks', 'own'),
  ('viewer', 'activity', 'none'),
  ('viewer', 'appraisal', 'none'),
  ('viewer', 'finance', 'view'),
  ('viewer', 'kpis', 'view'),
  ('viewer', 'my_day', 'view'),
  ('viewer', 'overview', 'view'),
  ('viewer', 'partners', 'view'),
  ('viewer', 'pipeline', 'view'),
  ('viewer', 'projects', 'view'),
  ('viewer', 'reports', 'view'),
  ('viewer', 'settings.app', 'none'),
  ('viewer', 'settings.finance', 'none'),
  ('viewer', 'settings.org', 'none'),
  ('viewer', 'settings.partners', 'none'),
  ('viewer', 'settings.performance', 'none'),
  ('viewer', 'settings.profile', 'own'),
  ('viewer', 'settings.work', 'none'),
  ('viewer', 'tasks', 'view')
) v (role_key, page_key, level)
join core.role r on r.key = v.role_key
where not exists (select 1 from core.role_page_level x
                  where x.role_id = r.id and x.page_key = v.page_key and x.deleted_at is null);

-- each role's starting capabilities, where it has none
insert into core.role_capability (role_id, capability_key, granted)
select r.id, v.capability_key, v.granted
from (values
  ('admin', 'finance.credit', true),
  ('admin', 'finance.credit_control', true),
  ('admin', 'finance.import', true),
  ('admin', 'org.sign_out', true),
  ('admin', 'partners.assign', true),
  ('admin', 'partners.identify', true),
  ('admin', 'partners.merge', true),
  ('admin', 'tasks.assign', true),
  ('head', 'finance.credit', true),
  ('head', 'finance.credit_control', true),
  ('head', 'finance.import', true),
  ('head', 'org.sign_out', false),
  ('head', 'partners.assign', true),
  ('head', 'partners.identify', true),
  ('head', 'partners.merge', true),
  ('head', 'tasks.assign', true),
  ('manager', 'finance.credit', true),
  ('manager', 'finance.credit_control', false),
  ('manager', 'finance.import', false),
  ('manager', 'org.sign_out', false),
  ('manager', 'partners.assign', true),
  ('manager', 'partners.identify', true),
  ('manager', 'partners.merge', false),
  ('manager', 'tasks.assign', true),
  ('member', 'finance.credit', false),
  ('member', 'finance.credit_control', false),
  ('member', 'finance.import', false),
  ('member', 'org.sign_out', false),
  ('member', 'partners.assign', false),
  ('member', 'partners.identify', false),
  ('member', 'partners.merge', false),
  ('member', 'tasks.assign', false),
  ('viewer', 'finance.credit', false),
  ('viewer', 'finance.credit_control', false),
  ('viewer', 'finance.import', false),
  ('viewer', 'org.sign_out', false),
  ('viewer', 'partners.assign', false),
  ('viewer', 'partners.identify', false),
  ('viewer', 'partners.merge', false),
  ('viewer', 'tasks.assign', false)
) v (role_key, capability_key, granted)
join core.role r on r.key = v.role_key
where not exists (select 1 from core.role_capability x
                  where x.role_id = r.id and x.capability_key = v.capability_key and x.deleted_at is null);

-- a new setting's default, written once as a company-wide row from the floor date (§3.2, V97): it answers for every
-- past day, and never overwrites a value an admin has set
insert into core.setting (key, department_id, value, valid_from, reason)
select v.key, null, v.value, date '2000-01-01', 'default'
from (values
  ('app.arabic_enabled', 'false'::jsonb),
  ('app.default_density', '"comfortable"'::jsonb),
  ('app.default_theme', '"direct"'::jsonb),
  ('app.export_formats', '["csv","xlsx"]'::jsonb),
  ('audit.recently_deleted_days', '30'::jsonb),
  ('audit.undo_window_hours', '24'::jsonb),
  ('auth.device_idle_days', '30'::jsonb),
  ('files.max_mb', '20'::jsonb),
  ('notify.kinds_enabled', '["assigned","helper_added","mentioned","changed_by_other","followed_change","decision_needed","report_issued","report_for_review","appraisal_step","import_done","alert_contract_expiring","alert_kpi_behind","alert_invoice_unpaid","alert_kpi_checkin"]'::jsonb),
  ('partner.id_format', '{"prefix":"DK-P","width":4}'::jsonb),
  ('partner.name_stop_words', '["شركة","مؤسسة","company","co","corp","corporation","ltd","limited","llc","inc","est"]'::jsonb),
  ('partner.one_code_per_partner', 'true'::jsonb),
  ('work.meeting_note_on_time_days', '1'::jsonb),
  ('work.no_update_days', '7'::jsonb),
  ('work.pipeline_weekly_target', '1'::jsonb),
  ('work.reminder_days_before_due', '1'::jsonb),
  ('work.week_starts_on', '"sunday"'::jsonb)
) v (key, value)
where not exists (select 1 from core.setting s where s.key = v.key);

select audit.end();
