import { DbError, unwrap } from '@/core/db/errors';
import { serviceDb } from '@/core/db/service';
import { adminRoute, requireLevel, textArg, uuidArg } from '@/core/auth/allow-list';
import { MUST_CHANGE, passwordOk } from '@/core/auth/password-rules';

/** Letters and digits nobody misreads: no 0/O, 1/l/I. */
const ALPHABET = 'ABCDEFGHJKLMNPQRSTUVWXYZabcdefghjkmnpqrstuvwxyz23456789';
function temporaryPassword(length = 14): string {
  const bytes = crypto.getRandomValues(new Uint8Array(length));
  return Array.from(bytes, (b) => ALPHABET[b % ALPHABET.length]).join('');
}

/**
 * Settings → People: Generate temporary password for a person (V441: random, 14 characters, shown once with Copy —
 * nobody types a password for someone else, nothing is mailed) — admins only, with a reason. Every auth user of the
 * person gets it and the must-change flag, so their next sign-in asks them to choose their own. Body: person_id, reason.
 */
export async function POST(request: Request) {
  return adminRoute(request, async (body) => {
    await requireLevel('settings.org', 'full');
    const personId = uuidArg(body, 'person_id') as string;
    const reason = textArg(body, 'reason');
    if (!reason) throw new DbError('RuleBroken', 'common.reason_required');
    const password = temporaryPassword();
    if (!passwordOk(password)) throw new DbError('RuleBroken', 'password.too_short');
    const state = unwrap(await serviceDb().rpc('person_auth_state', { p_person: personId }));
    if (!state.length) throw new DbError('RuleBroken', 'password.no_email');
    const admin = serviceDb().auth.admin;
    for (const row of state) {
      const { data: current } = await admin.getUserById(row.auth_user_id);
      const { error } = await admin.updateUserById(row.auth_user_id, {
        password,
        app_metadata: { ...(current?.user?.app_metadata ?? {}), [MUST_CHANGE]: true },
      });
      if (error) throw new DbError('Unavailable', 'common.unavailable', error.message);
    }
    // NEED (builder A, P3-2b): a logged request for "temporary password generated by <admin>, reason" — the sign-in
    // log's results do not include it yet; until then the change is visible only in the person's next sign-in.
    return { temporary_password: password };
  });
}
