/* Stress fixture — EXACT mirror of the live-DB batch `stress-2026-08-12`.
   The whale rows are generated by the same arithmetic as the SQL generate_series,
   so harness data == live data without transferring rows. Toggle with MOCK_STRESS=1. */

const MONTHS = ['January','February','March','April','May','June','July','August','September','October','November','December'];
const SVC = ['Flights','Hotels','Visas','Courses','Wallet top-up','Support Services','Transport','Insurance','Packages'];
const PROD = ['Corporate flight tickets','Hotel accommodation Riyadh','Business visa processing','Executive training course','Wallet top-up','Techtic support retainer','Airport transfer fleet','Travel insurance annual','Umrah group package'];

export function whaleRows() {
  const rows = [];
  for (let i = 0; i < 1200; i++) {
    const d = new Date(Date.UTC(2024, i % 32, 1 + (i * 7) % 27));
    const date = d.toISOString().slice(0, 10);
    const month = MONTHS[d.getUTCMonth()], quarter = 'Q' + (Math.floor(d.getUTCMonth() / 3) + 1);
    const t = 3000 + (i % 37) * 950 + (i % 7) * 111;
    const w = (i % 17 === 0) ? 500 : 0;
    const rev = t - w, cost = Math.round(rev * 0.82), prof = rev - cost;
    const unpaid = i % 13 === 0;
    rows.push({
      id: 'stz-amh-' + i, invoice_no: 'DP-AMH-' + (10000 + i), line_no: 1,
      zatca_dpin: (i % 11 === 0) ? null : 'TTIN-AMH-' + (10000 + i),
      client_group: 'Al-Mutlaq Holding Group', customer_raw_name: 'AL MUTLAQ HOLDING GROUP CO',
      invoice_date: date, month, quarter, year: d.getUTCFullYear(),
      products: PROD[i % 9], service_type: SVC[i % 9],
      record_type: (i % 20 === 0) ? 'tender' : 'b2b',
      total_incl_vat_sar: t, wallet_portion_sar: w, revenue_sar: rev, cost_sar: cost, profit_sar: prof,
      amount_received_sar: unpaid ? 0 : t, amount_remaining_sar: unpaid ? t : 0,
      integrity_status: unpaid ? 'pending' : 'verified_paid',
      origin: (i % 8 === 0) ? 'project' : 'booking',
      proposal_ref: (i % 8 === 0) ? 'DB-AMH-' + (i % 6) : null,
      source_batch: 'stress-2026-08-12', deleted_at: null, items: null,
    });
    if (i % 50 === 0) {
      const t2 = 1200 + (i % 5) * 300, c2 = Math.round(t2 * 0.85);
      rows.push({
        id: 'stz-amh2-' + i, invoice_no: 'DP-AMH-' + (10000 + i), line_no: 2,
        zatca_dpin: (i % 11 === 0) ? null : 'TTIN-AMH-' + (10000 + i),
        client_group: 'Al-Mutlaq Holding Group', customer_raw_name: 'AL MUTLAQ HOLDING GROUP CO',
        invoice_date: date, month, quarter, year: d.getUTCFullYear(),
        products: 'Hotel add-on nights', service_type: 'Hotels', record_type: 'b2b',
        total_incl_vat_sar: t2, wallet_portion_sar: 0, revenue_sar: t2, cost_sar: c2, profit_sar: t2 - c2,
        amount_received_sar: unpaid ? 0 : t2, amount_remaining_sar: unpaid ? t2 : 0,
        integrity_status: unpaid ? 'pending' : 'verified_paid',
        origin: (i % 8 === 0) ? 'project' : 'booking', proposal_ref: null,
        source_batch: 'stress-2026-08-12', deleted_at: null,
        items: [{ d: 'Deluxe room x3 nights', q: 3, u: 450 }, { d: 'Late checkout', q: 1, u: 150 }],
      });
    }
  }
  return rows;
}

const F = (no, ln, dpin, grp, rawn, date, prod, svc, rt, t, w, rev, cost, rec, rem, st, org, ref, items) => {
  const d = new Date(date + 'T00:00:00Z');
  return { id: 'stz-' + no.toLowerCase() + '-' + ln, invoice_no: no, line_no: ln, zatca_dpin: dpin, client_group: grp,
    customer_raw_name: rawn, invoice_date: date, month: MONTHS[d.getUTCMonth()], quarter: 'Q' + (Math.floor(d.getUTCMonth() / 3) + 1),
    year: d.getUTCFullYear(), products: prod, service_type: svc, record_type: rt, total_incl_vat_sar: t, wallet_portion_sar: w,
    revenue_sar: rev, cost_sar: cost, profit_sar: rev - cost, amount_received_sar: rec, amount_remaining_sar: rem,
    integrity_status: st, origin: org, proposal_ref: ref || null, source_batch: 'stress-2026-08-12', deleted_at: null, items: items || null };
};

export function smallRows() {
  const rows = [
    F('DP-BYT-1',1,'TTIN-BYT-1','Bayt Alsaghir Trading','BAYT ALSAGHIR TRADING EST','2026-07-22','Two flight tickets Riyadh-Dubai','Flights','b2b',4600,0,4600,3900,4600,0,'verified_paid','booking'),
    F('DP-SHM-1',1,'TTIN-SHM-1','Sahm Capital Aviation','SAHM CAPITAL AVIATION','2026-06-05','Executive charter booking','Flights','b2b',34500,0,34500,29000,34500,0,'verified_paid','booking'),
    F('DP-SHM-2',1,'TTIN-SHM-2','Sahm Capital Aviation','SAHM CAPITAL AVIATION','2026-07-03','Hotel block Jeddah','Hotels','b2b',12650,0,12650,10800,12650,0,'verified_paid','booking'),
    F('DP-SHM-3',1,null,'Sahm Capital Aviation','SAHM CAPITAL AVIATION','2026-07-28','Visa batch x6 — tax invoice pending','Visas','b2b',5175,0,5175,4300,0,5175,'pending','booking'),
    F('DP-SHM-4',1,'TTIN-SHM-4','Sahm Capital Aviation','SAHM CAPITAL AVIATION','2026-08-02','Credit note — cancelled charter leg','Flights','b2b',-8050,0,-8050,-6900,0,0,'credit_note','booking'),
    F('DP-SHM-5',1,'TTIN-SHM-5','Sahm Capital Aviation','SAHM CAPITAL AVIATION','2026-08-05','Internal test row — excluded from totals','Hotels','b2b',999,0,999,900,0,0,'excluded','booking'),
    F('DP-SHM-6',1,'TTIN-SHM-6','Sahm Capital Aviation','SAHM CAPITAL AVIATION','2026-08-08','Group booking deposit — half collected','Packages','b2b',18400,0,18400,15600,9200,9200,'pending','booking'),
    F('DP-JBL-1',1,'TTIN-JBL-1','Jabal Omar Development','JABAL OMAR DEVELOPMENT CO','2026-05-20','Full-year government travel program 2026','Packages','government',48500000,0,48500000,44135000,48500000,0,'verified_paid','project','DB-JBL-2026'),
    F('DP-DNA-1',1,'TTIN-DNA-1','Dana Medical Group','DANA MEDICAL GROUP','2026-07-26','Doctor conference flights','Flights','b2b',21850,0,21850,18500,21850,0,'verified_paid','booking'),
    F('DP-DNA-2',1,'TTIN-DNA-2','Dana Medical Group','DANA MEDICAL GROUP','2026-07-29','Hotel Riyadh 12 rooms','Hotels','b2b',16100,0,16100,14000,16100,0,'verified_paid','booking'),
    F('DP-DNA-3',1,'TTIN-DNA-3','Dana Medical Group','DANA MEDICAL GROUP','2026-08-01','Visas for visiting surgeons','Visas','b2b',6900,0,6900,5750,6900,0,'verified_paid','booking'),
    F('DP-DNA-4',1,'TTIN-DNA-4','Dana Medical Group','DANA MEDICAL GROUP','2026-08-03','Airport transfers month','Transport','b2b',3450,0,3450,2900,3450,0,'verified_paid','booking'),
    F('DP-DNA-5',1,'TTIN-DNA-5','Dana Medical Group','DANA MEDICAL GROUP','2026-08-05','Travel insurance staff','Insurance','b2b',5750,0,5750,4950,5750,0,'verified_paid','booking'),
    F('DP-DNA-6',1,'TTIN-DNA-6','Dana Medical Group','DANA MEDICAL GROUP','2026-08-07','Training course logistics','Courses','b2b',9200,0,9200,7800,9200,0,'verified_paid','project','DB-DNA-01'),
    F('DP-DNA-7',1,'TTIN-DNA-7','Dana Medical Group','DANA MEDICAL GROUP','2026-08-09','Wallet top-up','Wallet top-up','b2b',10000,10000,0,0,10000,0,'verified_paid','booking'),
    F('DP-DNA-8',1,null,'Dana Medical Group','DANA MEDICAL GROUP','2026-08-11','Umrah staff package — awaiting ZATCA','Packages','b2b',27600,0,27600,23400,0,27600,'pending','booking'),
    F('DP-IND-1',1,'TTIN-IND-1','MOHAMMED ALQAHTANI','MOHAMMED ALQAHTANI','2026-06-14','Family Umrah package','Packages','b2c',13800,0,13800,11700,13800,0,'verified_paid','booking'),
    F('DP-IND-2',1,null,'MOHAMMED ALQAHTANI','MOHAMMED ALQAHTANI','2026-08-01','Flight change fee','Flights','b2c',920,0,920,780,920,0,'verified_paid','booking'),
  ];
  const wadi = [
    [1,'Corporate flights August','Flights',5520],[2,'فندق مكة ٣ ليال × ١٢ غرفة','Hotels',14260],[3,'تأشيرات عمل × ٤','Visas',3680],
    [4,'Leadership training Dubai','Courses',8050],[5,'Wallet top-up August','Wallet top-up',5000],[6,'Techtic API support','Support Services',2300],
    [7,'نقل مطار شهري','Transport',1955],[8,'تأمين سفر سنوي','Insurance',4140],[9,'برنامج عمرة الموظفين','Packages',11500],
    [10,'Extra baggage handling','Flights',805],[11,'Late checkout block','Hotels',600],[12,'Visa renewal x2','Visas',1840],
  ];
  for (const [ln, p, s, amt] of wadi) {
    const cost = Math.round(amt * 0.8);
    rows.push(F('DP-WDI-100', ln, 'TTIN-WDI-100', 'Wadi Alkhadamat Co', 'WADI ALKHADAMAT COMPANY', '2026-08-06', p, s, 'b2b', amt, 0, amt, cost, amt, 0, 'verified_paid', 'project', 'DB-WDI-77',
      ln === 1 ? [{ d: 'RUH-JED-RUH x8 pax', q: 8, u: 690 }] : null));
  }
  return rows;
}

const B = (lid, name, nameAr, stage, rawStage, extra) => ({
  id: 'stz-' + lid, legacy_id: lid, name, name_ar: nameAr, stage, status: stage, source: 'stress',
  category: extra.category || null, segment: extra.segment || null, assigned_to: extra.assigned || null,
  account_manager: extra.am || null, tier: extra.tier || null, is_client: !!extra.client,
  converted_date: extra.conv || null, credit_limit: extra.credit || null, next_review: extra.review || null,
  funnel_id: extra.funnel || null, funnel_details: extra.fd || {}, needs_manual_confirmation: !!extra.dup,
  confirmation_reason: extra.dupWhy || null, lost_reason: extra.lost || null, direct_client_id: extra.did || null,
  total_sar: null, website: null, channels: [], prefs: {}, airline_deals: [], pricing: [], notes: null,
  created_at: '2026-08-12T04:26:00Z', updated_at: '2026-08-12T04:26:00Z', scrub_run_id: 'stress-2026-08-12',
  raw: Object.assign({ id: lid, name, nameAr, isClient: !!extra.client, stage: rawStage, assignedTo: extra.assigned || null,
    accountManager: extra.am || null, tier: extra.tier || null, nextReview: extra.review || null,
    directClientId: extra.did || null, funnelKey: extra.fk || null, contacts: [], activities: [], lostReason: extra.lost || null }, extra.raw || {}),
});

export function applyStress(TABLES) {
  const fid = k => { const f = (TABLES.funnels || []).find(x => x.key === k); return f ? f.id : null; };
  const biz = [
    B('st_mutlaq','Al-Mutlaq Holding Group','مجموعة المطلق القابضة','won','Won',{client:1,conv:'2026-05-10',category:'Corporate',segment:'Conglomerate',assigned:'Abdelrahman Hasan',am:'Saif Abdulelah',tier:'Key',credit:500000,review:'2026-08-01',did:'950',raw:{billingAccounts:[{id:'950',mode:'Postpaid'},{id:'951',mode:'Prepaid'},{id:'952',mode:'Tender'}],agreement:'Master services agreement 2026 — postpaid monthly, SLA 2h, dedicated desk.'}}),
    B('st_bayt','Bayt Alsaghir Trading','بيت الصغير للتجارة','won','Won',{client:1,conv:'2026-07-20',segment:'SME',category:'Trading',assigned:'Assem Alsweed',am:'Assem Alsweed',did:'961'}),
    B('st_nujoom','Nujoom Al-Khaleej Events','نجوم الخليج للفعاليات','won','Won',{client:1,conv:'2026-08-09',segment:'Events',category:'MICE',assigned:'Saif Abdulelah',am:'Saif Abdulelah',review:'2026-09-15'}),
    B('st_fajr','مؤسسة الفجر للسياحة والسفر','مؤسسة الفجر للسياحة والسفر','contacted','Contacted',{segment:'Travel agency',category:'Travel Trade',assigned:'Abdulaziz Alreshody',funnel:fid('travel_trade'),fk:'travel_trade',fd:{mot_license:'73104882',iata:'No'}}),
    B('st_noorwings','Al Noor Wings Travel','أجنحة النور للسفر','new','New',{segment:'Travel agency',category:'Travel Trade',assigned:'Kareem Wahdan',funnel:fid('travel_trade'),fk:'travel_trade',dup:1,dupWhy:'Possible duplicate of "Alnoorwings Travel" (st_noorwings2) — same family name, verify CR before any merge'}),
    B('st_noorwings2','Alnoorwings Travel','النور وينجز','new','New',{segment:'Travel agency',category:'Travel Trade',assigned:'Kareem Wahdan',funnel:fid('travel_trade'),fk:'travel_trade',dup:1,dupWhy:'Possible duplicate of "Al Noor Wings Travel" (st_noorwings) — same family name, verify CR before any merge'}),
    B('st_sahm','Sahm Capital Aviation','سهم كابيتال للطيران','won','Won',{client:1,conv:'2026-06-01',segment:'Aviation',category:'Corporate',assigned:'Mohammed Alhusaini',am:'Mohammed Alhusaini',credit:80000,did:'963'}),
    B('st_wadi','Wadi Alkhadamat Co','وادي الخدمات','won','Won',{client:1,conv:'2026-07-01',segment:'Services',category:'Corporate',assigned:'Assem Alsweed',am:'Saif Abdulelah',did:'964'}),
    B('st_jabal','Jabal Omar Development','جبل عمر للتطوير','won','Won',{client:1,conv:'2026-04-15',segment:'Real estate',category:'Government',assigned:'Abdelrahman Hasan',am:'Abdelrahman Hasan',tier:'Key',review:'2026-12-01',did:'965'}),
    B('st_longname','The International Consolidated Company for Travel Tourism Hajj Umrah and Business Services of the Eastern Region Limited','الشركة العالمية الموحدة للسفر والسياحة والحج والعمرة وخدمات الأعمال للمنطقة الشرقية المحدودة','in_discussion','Qualified',{segment:'Travel services',category:'Corporate',assigned:'Saif Abdulelah',funnel:fid('outreach'),fk:'outreach'}),
    B('st_lostco','Riyadh Steel Works','مصنع الرياض للحديد','lost','Lost',{segment:'Industrial',category:'Corporate',assigned:'Kareem Wahdan',funnel:fid('outreach'),fk:'outreach',lost:'Chose a competitor on price — re-approach after Q4 budget cycle'}),
    B('st_holdco','Manafea Holding','منافع القابضة','on_hold','On hold',{segment:'Investment',category:'Corporate',assigned:'Abdelrahman Hasan',funnel:fid('partners_tenders'),fk:'partners_tenders',raw:{onHold:{until:'2026-10-01',why:'Budget frozen till new fiscal year'}}}),
    B('st_webb2b','Masar Alarabia Logistics','مسار العربية للخدمات اللوجستية','contacted','Contacted',{segment:'Logistics',category:'B2B',assigned:'Abdulaziz Alreshody',funnel:fid('website_form_b2b'),fk:'website_form_b2b',fd:{inquiry_type:'Corporate travel desk',service_requested:'Flights + hotels',submitted_on:'2026-08-02'}}),
    B('st_inbound','Qmam Alfaya Events','قمم الفيا للفعاليات','proposal','Proposal',{segment:'Events',category:'MICE',assigned:'Saif Abdulelah',funnel:fid('inbound'),fk:'inbound',fd:{original_message:'Need travel partner for 3 conferences',channel:'WhatsApp'}}),
    B('st_tender','Sidra Development Authority','هيئة سدرة للتطوير','proposal','Proposal',{segment:'Government',category:'Tender',assigned:'Mohammed Alhusaini',funnel:fid('partners_tenders'),fk:'partners_tenders',fd:{tender_value:'2400000',tender_deadline:'2026-09-15',tender_status:'Proposal submitted'}}),
    B('st_pastinv','Gulf Bridge Contracting','جسر الخليج للمقاولات','contacted','Contacted',{segment:'Contracting',category:'Corporate',assigned:'Abdelrahman Hasan',funnel:fid('past_invoices'),fk:'past_invoices',fd:{lifetime_billed_sar:'182400',invoice_count:'7',last_dpin:'TTIN-88121',reapproach_angle:'Unpaid draft of 30K — warm reopening'}}),
    B('st_dana','Dana Medical Group','مجموعة دانة الطبية','won','Won',{client:1,conv:'2026-07-25',segment:'Healthcare',category:'Corporate',assigned:'Kareem Wahdan',am:'Abdelrahman Hasan',review:'2026-11-20',did:'967'}),
    B('st_manycontacts','Horizon Education Co','آفاق التعليم','in_discussion','Qualified',{segment:'Education',category:'B2B',assigned:'Assem Alsweed',funnel:fid('website_form_entity'),fk:'website_form_entity'}),
    B('st_barecase','Blank Slate Trading','بلانك سليت','new','New',{}),
  ];
  TABLES.businesses.push(...biz);
  TABLES.finance_invoices.push(...whaleRows(), ...smallRows());
  TABLES.finance_client_links.push(
    { id: 'stzl-1', client_group: 'Al-Mutlaq Holding Group', business_id: 'stz-st_mutlaq', is_client: true, note: 'stress', credit_balance_sar: 500000 },
    { id: 'stzl-2', client_group: 'Bayt Alsaghir Trading', business_id: 'stz-st_bayt', is_client: true, note: 'stress', credit_balance_sar: 0 },
    { id: 'stzl-3', client_group: 'Nujoom Al-Khaleej Events', business_id: 'stz-st_nujoom', is_client: true, note: 'stress — no invoices yet', credit_balance_sar: 0 },
    { id: 'stzl-4', client_group: 'Sahm Capital Aviation', business_id: 'stz-st_sahm', is_client: true, note: 'stress', credit_balance_sar: 15000 },
    { id: 'stzl-5', client_group: 'Wadi Alkhadamat Co', business_id: 'stz-st_wadi', is_client: true, note: 'stress', credit_balance_sar: 0 },
    { id: 'stzl-6', client_group: 'Jabal Omar Development', business_id: 'stz-st_jabal', is_client: true, note: 'stress', credit_balance_sar: 0 },
    { id: 'stzl-7', client_group: 'Dana Medical Group', business_id: 'stz-st_dana', is_client: true, note: 'stress', credit_balance_sar: 0 },
  );
  // contacts also live inside the company record itself (raw.contacts) — mirror the live UPDATE
  const CROLES = ['CEO office','Procurement','Finance','Travel desk','HR','Legal','IT','Executive assistant'];
  const bz = lid => biz.find(b => b.legacy_id === lid);
  bz('st_mutlaq').raw.contacts = [...Array(8)].map((_, j) => ({ name: 'Mutlaq Contact ' + (j + 1), role: CROLES[j], email: 'contact' + (j + 1) + '@almutlaq.example', phone: '+9665012000' + String(j + 1).padStart(2, '0') }));
  bz('st_manycontacts').raw.contacts = [...Array(15)].map((_, j) => ({ name: 'Horizon Contact ' + (j + 1), role: 'Branch ' + (j + 1), email: 'branch' + (j + 1) + '@horizonedu.example', phone: '+9665013000' + String(j + 1).padStart(2, '0') }));
  bz('st_bayt').raw.contacts = [{ name: 'Saleh Alsaghir', role: 'Owner', email: 'saleh@baytalsaghir.example', phone: '+966501400001' }];
  for (let i = 1; i <= 8; i++) TABLES.contacts.push({ id: 'stzc-m' + i, business_id: 'stz-st_mutlaq', name: 'Mutlaq Contact ' + i, role: CROLES[i - 1], email: 'contact' + i + '@almutlaq.example', phone: '+9665012000' + String(i).padStart(2, '0'), source: 'stress-2026-08-12' });
  for (let i = 1; i <= 15; i++) TABLES.contacts.push({ id: 'stzc-h' + i, business_id: 'stz-st_manycontacts', name: 'Horizon Contact ' + i, role: 'Branch ' + i, email: 'branch' + i + '@horizonedu.example', phone: '+9665013000' + String(i).padStart(2, '0'), source: 'stress-2026-08-12' });
  TABLES.contacts.push({ id: 'stzc-b1', business_id: 'stz-st_bayt', name: 'Saleh Alsaghir', role: 'Owner', email: 'saleh@baytalsaghir.example', phone: '+966501400001', source: 'stress-2026-08-12' });
}
