#!/usr/bin/env node
// @ts-check
// The TypeScript types of the `api` schema (the one door — A6), generated from the database the migrations built, so
// the app's calls to api.* are checked by the compiler instead of typed by hand (V114).
//
//   node scripts/db/gen-types.mjs            write src/core/db/database.types.ts from the local Supabase stack
//   node scripts/db/gen-types.mjs --check    fail when the committed file differs from what the stack generates (CI)
//
// Needs the Supabase CLI (`supabase`, or SUPABASE_BIN) and a running local stack (`supabase start`).
import { spawnSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import * as prettier from 'prettier';

const V2 = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');
const OUT = path.join(V2, 'src', 'core', 'db', 'database.types.ts');
const HEADER =
  '// Generated by `node scripts/db/gen-types.mjs` from the migrations (the `api` schema only). Do not edit by hand:\n' +
  '// change a migration, rebuild the stack and run the script again. CI fails when this file is out of date (V114).\n';

const check = process.argv.includes('--check');
const bin = process.env.SUPABASE_BIN || 'supabase';
const r = spawnSync(bin, ['gen', 'types', 'typescript', '--local', '--schema', 'api'], {
  cwd: V2,
  encoding: 'utf8',
  maxBuffer: 16 << 20,
});
if (r.error || r.status !== 0) {
  console.error(`supabase gen types failed:\n${r.error ?? r.stderr}`);
  process.exit(1);
}
const config = (await prettier.resolveConfig(OUT)) ?? {};
const generated = await prettier.format(HEADER + r.stdout, { ...config, filepath: OUT });

if (check) {
  const current = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : '';
  if (current !== generated) {
    console.error(
      `${path.relative(V2, OUT)} is out of date with the migrations — run \`node scripts/db/gen-types.mjs\` and commit it`,
    );
    process.exit(1);
  }
  console.log(`${path.relative(V2, OUT)} matches the migrations`);
} else {
  fs.writeFileSync(OUT, generated);
  console.log(`wrote ${path.relative(V2, OUT)}`);
}
