// Generated by `node scripts/db/gen-types.mjs` from the migrations (the `api` schema only). Do not edit by hand:
// change a migration, rebuild the stack and run the script again. CI fails when this file is out of date (V114).

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  api: {
    Tables: {
      [_ in never]: never;
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      access_clear_person_capability: {
        Args: { p_capability: string; p_person: string; p_reason: string };
        Returns: Json;
      };
      access_clear_person_level: { Args: { p_page: string; p_person: string; p_reason: string }; Returns: Json };
      access_matrix: { Args: Record<PropertyKey, never>; Returns: Json };
      access_of_person: { Args: { p_person: string }; Returns: Json };
      access_set_person_capability: {
        Args: { p_capability: string; p_granted: boolean; p_person: string; p_reason: string };
        Returns: Json;
      };
      access_set_person_level: {
        Args: { p_level: 'none' | 'view' | 'own' | 'full'; p_page: string; p_person: string; p_reason: string };
        Returns: Json;
      };
      access_set_person_role: { Args: { p_person: string; p_reason: string; p_role: string }; Returns: Json };
      access_set_role_capability: {
        Args: { p_capability: string; p_granted: boolean; p_reason: string; p_role: string };
        Returns: Json;
      };
      access_set_role_level: {
        Args: { p_level: 'none' | 'view' | 'own' | 'full'; p_page: string; p_reason: string; p_role: string };
        Returns: Json;
      };
      auth_user_of: { Args: { p_email: string }; Returns: string };
      device_sign_out: { Args: { p_device?: string }; Returns: number };
      device_sign_out_others: { Args: Record<PropertyKey, never>; Returns: number };
      device_touch: { Args: Record<PropertyKey, never>; Returns: string };
      me: { Args: Record<PropertyKey, never>; Returns: Json };
      my_devices: {
        Args: Record<PropertyKey, never>;
        Returns: {
          device_label: string;
          id: string;
          last_seen_at: string;
          signed_in_at: string;
          this_device: boolean;
        }[];
      };
      person_auth_link: { Args: { p_auth_user_id: string; p_email: string }; Returns: Json };
      person_auth_state: {
        Args: { p_person: string };
        Returns: {
          allowed: boolean;
          auth_user_id: string;
          email: string;
        }[];
      };
      person_devices: {
        Args: { p_person: string };
        Returns: {
          device_label: string;
          id: string;
          last_seen_at: string;
          signed_in_at: string;
        }[];
      };
      person_email_add: {
        Args: { p_email: string; p_person: string; p_primary?: boolean; p_reason?: string };
        Returns: Json;
      };
      person_email_remove: { Args: { p_id: string; p_reason: string }; Returns: Json };
      person_sign_out: { Args: { p_device?: string; p_person: string }; Returns: number };
      sign_in_check: { Args: { p_email: string; p_user_agent?: string }; Returns: string };
      sign_in_complete: {
        Args: { p_device_label?: string; p_provider?: string; p_user_agent?: string };
        Returns: string;
      };
      sign_in_event: {
        Args: { p_detail?: string; p_email: string; p_provider?: string; p_result: string; p_user_agent?: string };
        Returns: undefined;
      };
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};

type DatabaseWithoutInternals = Omit<Database, '__InternalSupabase'>;

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, 'public'>];

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    keyof (DefaultSchema['Tables'] & DefaultSchema['Views']) | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Views'])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Views'])[TableName] extends {
      Row: infer R;
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema['Tables'] & DefaultSchema['Views'])
    ? (DefaultSchema['Tables'] & DefaultSchema['Views'])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R;
      }
      ? R
      : never
    : never;

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables'] | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables']
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'][TableName] extends {
      Insert: infer I;
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables']
    ? DefaultSchema['Tables'][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I;
      }
      ? I
      : never
    : never;

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables'] | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables']
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'][TableName] extends {
      Update: infer U;
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables']
    ? DefaultSchema['Tables'][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U;
      }
      ? U
      : never
    : never;

export type Enums<
  DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema['Enums'] | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions['schema']]['Enums']
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions['schema']]['Enums'][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema['Enums']
    ? DefaultSchema['Enums'][DefaultSchemaEnumNameOrOptions]
    : never;

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    keyof DefaultSchema['CompositeTypes'] | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions['schema']]['CompositeTypes']
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions['schema']]['CompositeTypes'][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema['CompositeTypes']
    ? DefaultSchema['CompositeTypes'][PublicCompositeTypeNameOrOptions]
    : never;

export const Constants = {
  api: {
    Enums: {},
  },
} as const;
