// Generated by `node scripts/db/gen-types.mjs` from the migrations (the `api` schema only). Do not edit by hand:
// change a migration, rebuild the stack and run the script again. CI fails when this file is out of date (V114).

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  api: {
    Tables: {
      [_ in never]: never;
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      access_clear_person_capability: {
        Args: { p_capability: string; p_person: string; p_reason: string };
        Returns: Json;
      };
      access_clear_person_level: { Args: { p_page: string; p_person: string; p_reason: string }; Returns: Json };
      access_clear_team_level: { Args: { p_page: string; p_reason: string; p_team: string }; Returns: Json };
      access_matrix: { Args: Record<PropertyKey, never>; Returns: Json };
      access_of_person: { Args: { p_person: string }; Returns: Json };
      access_set_person_capability: {
        Args: { p_capability: string; p_granted: boolean; p_person: string; p_reason: string };
        Returns: Json;
      };
      access_set_person_level: {
        Args: { p_level: 'none' | 'view' | 'own' | 'full'; p_page: string; p_person: string; p_reason: string };
        Returns: Json;
      };
      access_set_person_role: { Args: { p_person: string; p_reason: string; p_role: string }; Returns: Json };
      access_set_role_capability: {
        Args: { p_capability: string; p_granted: boolean; p_reason: string; p_role: string };
        Returns: Json;
      };
      access_set_role_level: {
        Args: { p_level: 'none' | 'view' | 'own' | 'full'; p_page: string; p_reason: string; p_role: string };
        Returns: Json;
      };
      access_set_team_level: {
        Args: { p_level: 'none' | 'view' | 'own' | 'full'; p_page: string; p_reason: string; p_team: string };
        Returns: Json;
      };
      achievement: { Args: { p_id: string }; Returns: Json };
      achievement_categories: { Args: { p_department?: string; p_plan?: string; p_year?: number }; Returns: Json };
      achievement_categories_remove: { Args: { p_ids: string[]; p_reason?: string }; Returns: Json };
      achievement_category_save: {
        Args: { p_id: string; p_plan: string; p_values: Json; p_version?: number };
        Returns: Json;
      };
      achievement_line: { Args: { p_id: string; p_locale?: string }; Returns: string };
      achievement_log: { Args: { p_participants?: string[]; p_refs?: Json; p_values: Json }; Returns: Json };
      achievement_move: { Args: { p_id: string; p_reason: string; p_to: string; p_version: number }; Returns: Json };
      achievement_participants_set: { Args: { p_id: string; p_people: string[] }; Returns: Json };
      achievement_ref_add: { Args: { p_id: string; p_system: string; p_url?: string; p_value: string }; Returns: Json };
      achievement_refs_remove: { Args: { p_ids: string[]; p_reason?: string }; Returns: Json };
      achievement_repeats: {
        Args: { p_category: string; p_on?: string; p_partner: string; p_title: string };
        Returns: Json;
      };
      achievement_update: {
        Args: { p_id: string; p_reason?: string; p_values: Json; p_version: number };
        Returns: Json;
      };
      achievements: { Args: { p_filter?: Json; p_limit?: number; p_offset?: number }; Returns: Json };
      achievements_assign: { Args: { p_ids: string[]; p_owner: string; p_reason?: string }; Returns: Json };
      achievements_remove: { Args: { p_ids: string[]; p_reason: string }; Returns: Json };
      action_item_add: { Args: { p_task: string; p_values: Json }; Returns: Json };
      action_item_done: { Args: { p_done: boolean; p_id: string; p_on?: string }; Returns: Json };
      action_item_update: { Args: { p_id: string; p_values: Json; p_version: number }; Returns: Json };
      action_items_remove: { Args: { p_ids: string[]; p_reason?: string }; Returns: Json };
      activity: {
        Args: { p_actor?: string; p_before?: string; p_entity?: string; p_limit?: number; p_since?: string };
        Returns: Json;
      };
      activity_log: {
        Args: {
          p_body?: string;
          p_happened_on?: string;
          p_mentions?: string[];
          p_next_step?: string;
          p_next_step_on?: string;
          p_outcome?: string;
          p_partner: string;
          p_type: string;
        };
        Returns: Json;
      };
      app_settings: { Args: Record<PropertyKey, never>; Returns: Json };
      auth_ticket_issue: { Args: { p_kind: string; p_person: string; p_target: string }; Returns: string };
      auth_user_of: { Args: { p_email: string }; Returns: string };
      backfill_achievement_keys_held: { Args: { p_keys: string[] }; Returns: Json };
      backfill_achievements: { Args: { p_request: Json }; Returns: Json };
      backfill_keys_held: { Args: { p_keys: string[] }; Returns: Json };
      backfill_tasks: { Args: { p_request: Json }; Returns: Json };
      campaign_code_add: {
        Args: {
          p_code: string;
          p_name: string;
          p_owner: string;
          p_reason: string;
          p_valid_from: string;
          p_valid_to: string;
        };
        Returns: Json;
      };
      can_see: { Args: { p_entity: string; p_id: string }; Returns: boolean };
      client_id_close: { Args: { p_closed_on: string; p_id: string; p_reason: string }; Returns: Json };
      client_id_reopen: { Args: { p_id: string; p_reason: string }; Returns: Json };
      code_terms_add: {
        Args: {
          p_approved_by: string;
          p_approved_on: string;
          p_campaign: string;
          p_countries?: string[];
          p_effective_from: string;
          p_fee_percent: number;
          p_identifier: string;
          p_review_on?: string;
          p_services?: string[];
          p_tiers?: Json;
        };
        Returns: Json;
      };
      contact_save: { Args: { p_id: string; p_partner: string; p_values: Json; p_version?: number }; Returns: Json };
      contacts_remove: { Args: { p_ids: string[]; p_reason?: string }; Returns: Json };
      contract_renewal_task: { Args: { p_contract: string }; Returns: Json };
      contract_save: {
        Args: { p_id: string; p_partner: string; p_reason?: string; p_values: Json; p_version?: number };
        Returns: Json;
      };
      contracts: { Args: { p_partner: string; p_side?: string }; Returns: Json };
      contracts_remove: { Args: { p_ids: string[]; p_reason?: string }; Returns: Json };
      credit_limit_set: {
        Args: {
          p_amount: number;
          p_approved_by: string;
          p_effective_from: string;
          p_partner: string;
          p_reason: string;
        };
        Returns: Json;
      };
      department_save: {
        Args: {
          p_code: string;
          p_head?: string;
          p_id: string;
          p_name_ar?: string;
          p_name_en: string;
          p_reason?: string;
          p_version?: number;
        };
        Returns: Json;
      };
      device_sign_out: { Args: { p_device?: string }; Returns: number };
      device_sign_out_others: { Args: Record<PropertyKey, never>; Returns: number };
      device_touch: { Args: Record<PropertyKey, never>; Returns: string };
      escalate: { Args: { p_entity: string; p_id: string; p_note: string; p_to: string }; Returns: Json };
      file_begin: {
        Args: {
          p_entity: string;
          p_id: string;
          p_kind: string;
          p_mime: string;
          p_original_name: string;
          p_purpose: string;
          p_review_on?: string;
          p_sensitivity?: string;
          p_side?: string;
          p_size: number;
        };
        Returns: Json;
      };
      file_download: { Args: { p_id: string; p_locale?: string }; Returns: Json };
      file_finish: { Args: { p_id: string; p_sha256: string }; Returns: Json };
      file_review_set: { Args: { p_id: string; p_review_on: string; p_version?: number }; Returns: Json };
      files: { Args: { p_entity: string; p_id: string; p_side?: string }; Returns: Json };
      files_remove: { Args: { p_ids: string[]; p_reason?: string }; Returns: Json };
      finance_channel_set: {
        Args: { p_channel: string; p_invoice: string; p_person?: string; p_reason?: string };
        Returns: Json;
      };
      finance_closed_months: { Args: Record<PropertyKey, never>; Returns: Json };
      finance_difference_counts: {
        Args: Record<PropertyKey, never>;
        Returns: {
          differences: number;
          invoice_id: string;
        }[];
      };
      finance_difference_decide: {
        Args: { p_choice: string; p_id: string; p_reason?: string; p_version: number };
        Returns: Json;
      };
      finance_differences: {
        Args: { p_invoice?: string };
        Returns: {
          field: string;
          from_import: string;
          id: string;
          import_time: string;
          invoice_id: string;
          invoice_ref: string;
          line_no: number;
          mine: string;
          row_id: string;
          row_table: string;
          version: number;
        }[];
      };
      finance_health: { Args: { p_from?: string; p_to?: string }; Returns: Json };
      finance_import: {
        Args: {
          p_dry_run?: boolean;
          p_export_time: string;
          p_file: string;
          p_file_name?: string;
          p_rows: Json;
          p_sha256?: string;
        };
        Returns: Json;
      };
      finance_import_map: { Args: { p_source?: string }; Returns: Json };
      finance_import_recognise: { Args: { p_headers: string[]; p_source: string }; Returns: Json };
      finance_income_by_service: { Args: { p_from: string; p_to: string }; Returns: Json };
      finance_month_close: { Args: { p_month: string; p_note?: string }; Returns: Json };
      finance_not_invoiced: { Args: { p_from?: string; p_to?: string }; Returns: Json };
      finance_period: { Args: { p_from: string; p_to: string }; Returns: Json };
      finance_period_units: {
        Args: { p_from: string; p_to: string };
        Returns: {
          channel: string;
          cost: number;
          cost_is: string;
          counted: boolean;
          dpin: string;
          excluded_reason: string;
          invoice_id: string;
          loss: boolean;
          month_on: string;
          paid_on: string;
          partner_id: string;
          profit: number;
          ref: string;
          revenue: number;
          unit_kind: string;
        }[];
      };
      finance_proposal_decide: { Args: { p_id: string; p_reason?: string; p_tick: boolean }; Returns: Json };
      finance_row_add: { Args: { p_fields: Json; p_reason?: string; p_table: string }; Returns: Json };
      finance_row_edit: {
        Args: { p_fields: Json; p_id: string; p_reason?: string; p_table: string; p_version: number };
        Returns: Json;
      };
      finance_rows_remove: { Args: { p_ids: string[]; p_reason: string; p_table: string }; Returns: Json };
      finance_search: { Args: { p_limit?: number; p_text: string }; Returns: Json };
      follow: { Args: { p_entity: string; p_id: string; p_on?: boolean }; Returns: boolean };
      following: { Args: { p_entity: string; p_id: string }; Returns: boolean };
      from_note: { Args: { p_entity: string; p_id: string }; Returns: Json };
      hover_partner: { Args: { p_id: string }; Returns: Json };
      hover_person: { Args: { p_id: string }; Returns: Json };
      identifier_add: {
        Args: {
          p_kind: string;
          p_note?: string;
          p_partner: string;
          p_reason: string;
          p_second_code?: boolean;
          p_subkind?: string;
          p_valid_from?: string;
          p_valid_to?: string;
          p_value: string;
        };
        Returns: Json;
      };
      identifier_block_add: {
        Args: { p_kind: string; p_match: string; p_reason: string; p_value: string };
        Returns: Json;
      };
      identifier_remove: { Args: { p_id: string; p_reason: string }; Returns: Json };
      individual_add: { Args: { p_name: string; p_reason?: string }; Returns: Json };
      list: { Args: { p_include_retired?: boolean; p_list: string }; Returns: Json };
      list_remove: { Args: { p_id: string; p_list: string; p_reason?: string }; Returns: Json };
      list_retire: { Args: { p_id: string; p_list: string; p_reason: string; p_replacement: string }; Returns: Json };
      list_save: {
        Args: { p_id: string; p_list: string; p_reason?: string; p_values: Json; p_version?: number };
        Returns: Json;
      };
      list_usage: { Args: { p_id: string; p_list: string }; Returns: Json };
      me: { Args: Record<PropertyKey, never>; Returns: Json };
      my_day: { Args: { p_limit?: number; p_offset?: number; p_scope?: string; p_since?: string }; Returns: Json };
      my_devices: {
        Args: Record<PropertyKey, never>;
        Returns: {
          device_label: string;
          id: string;
          last_seen_at: string;
          signed_in_at: string;
          this_device: boolean;
        }[];
      };
      my_note: { Args: { p_id: string }; Returns: Json };
      my_notes_remove: { Args: { p_ids: string[]; p_reason?: string }; Returns: Json };
      note_add: {
        Args: {
          p_body: string;
          p_entity: string;
          p_happened_on?: string;
          p_id: string;
          p_kind: string;
          p_mentions?: string[];
        };
        Returns: Json;
      };
      note_capture: { Args: { p_kind: string; p_mentions?: string[]; p_values?: Json }; Returns: Json };
      note_edit: { Args: { p_id: string; p_mentions?: string[]; p_values: Json; p_version: number }; Returns: Json };
      note_finish_meeting: { Args: { p_note: string; p_values?: Json }; Returns: Json };
      note_turn_into: { Args: { p_kind: string; p_note: string; p_values?: Json }; Returns: Json };
      note_update: { Args: { p_id: string; p_mentions?: string[]; p_values: Json; p_version: number }; Returns: Json };
      note_wrap_up: { Args: { p_choices: Json; p_day: string }; Returns: Json };
      notes: {
        Args: { p_entity: string; p_id: string; p_kinds?: string[]; p_limit?: number; p_offset?: number };
        Returns: Json;
      };
      notes_remove: { Args: { p_ids: string[]; p_reason?: string }; Returns: Json };
      notifications: { Args: { p_before?: string; p_limit?: number; p_tab?: string }; Returns: Json };
      notifications_mark_read: { Args: { p_ids?: string[] }; Returns: number };
      notifications_snooze: { Args: { p_ids: string[]; p_until: string }; Returns: number };
      notifications_unread: { Args: Record<PropertyKey, never>; Returns: number };
      org: { Args: Record<PropertyKey, never>; Returns: Json };
      own_password_set: { Args: { p_auth_user: string; p_keep_session: string }; Returns: Json };
      page_seen: { Args: { p_page: string }; Returns: string };
      partner: { Args: { p_id: string }; Returns: Json };
      partner_bulk_assign: {
        Args: { p_ids: string[]; p_owner: string; p_priority: string; p_reason?: string; p_side: string };
        Returns: Json;
      };
      partner_create: { Args: { p_partner: Json; p_reason?: string }; Returns: Json };
      partner_merge: { Args: { p_kept: string; p_merged: string; p_reason: string }; Returns: Json };
      partner_owner_set: {
        Args: { p_from?: string; p_id: string; p_person: string; p_reason?: string; p_side: string };
        Returns: Json;
      };
      partner_references: { Args: { p_partner: string }; Returns: Json };
      partner_side_off: { Args: { p_id: string; p_reason?: string; p_side: string; p_until?: string }; Returns: Json };
      partner_side_set: { Args: { p_id: string; p_reason?: string; p_side: string; p_values: Json }; Returns: Json };
      partner_status_set: {
        Args: {
          p_effective_on?: string;
          p_id: string;
          p_note?: string;
          p_reason_id?: string;
          p_side: string;
          p_status: string;
        };
        Returns: Json;
      };
      partner_update: { Args: { p_changes: Json; p_id: string; p_reason?: string; p_version: number }; Returns: Json };
      partners: { Args: { p_filters?: Json; p_limit?: number; p_offset?: number }; Returns: Json };
      password_changed: { Args: { p_auth_user: string }; Returns: Json };
      people: { Args: Record<PropertyKey, never>; Returns: Json };
      people_match: { Args: { p_names: string[] }; Returns: Json };
      people_without_password: { Args: Record<PropertyKey, never>; Returns: Json };
      person_account_set: { Args: { p_account: string; p_id: string; p_reason: string }; Returns: Json };
      person_auth_found: { Args: { p_auth_user: string }; Returns: Json };
      person_auth_link: { Args: { p_auth_user_id: string; p_email: string }; Returns: Json };
      person_auth_state: {
        Args: { p_person: string };
        Returns: {
          allowed: boolean;
          auth_user_id: string;
          email: string;
        }[];
      };
      person_create: { Args: { p_person: Json; p_reason?: string }; Returns: Json };
      person_devices: {
        Args: { p_person: string };
        Returns: {
          device_label: string;
          id: string;
          last_seen_at: string;
          signed_in_at: string;
        }[];
      };
      person_email_add: {
        Args: { p_email: string; p_person: string; p_primary?: boolean; p_reason?: string };
        Returns: Json;
      };
      person_email_remove: { Args: { p_id: string; p_reason: string }; Returns: Json };
      person_emails_unlinked: { Args: { p_person: string }; Returns: string[] };
      person_leave: {
        Args: { p_id: string; p_left_on?: string; p_reason: string; p_reassign_to?: string };
        Returns: Json;
      };
      person_open_work: { Args: { p_id: string }; Returns: Json };
      person_password_set: { Args: { p_person: string; p_reason: string; p_replace?: boolean }; Returns: Json };
      person_sign_out: { Args: { p_device?: string; p_person: string }; Returns: number };
      person_switch: { Args: { p_id: string; p_on: boolean; p_reason: string; p_reassign_to?: string }; Returns: Json };
      person_update: { Args: { p_changes: Json; p_id: string; p_reason?: string; p_version: number }; Returns: Json };
      plan_open: { Args: { p_department: string; p_name?: string; p_year: number }; Returns: Json };
      plans: { Args: { p_department?: string }; Returns: Json };
      profile_update: { Args: { p_changes: Json; p_person_version?: number; p_version?: number }; Returns: Json };
      project: { Args: { p_id: string }; Returns: Json };
      project_health_set: {
        Args: { p_happened_on?: string; p_health: string; p_line: string; p_project: string };
        Returns: Json;
      };
      project_save: { Args: { p_id: string; p_values: Json; p_version?: number }; Returns: Json };
      projects: { Args: { p_filter?: Json; p_limit?: number; p_offset?: number }; Returns: Json };
      projects_remove: { Args: { p_ids: string[]; p_reason?: string }; Returns: Json };
      recently_deleted: { Args: { p_limit?: number }; Returns: Json };
      record_history: { Args: { p_entity: string; p_id: string }; Returns: Json };
      reference_save: {
        Args: { p_id: string; p_partner: string; p_reason?: string; p_values: Json; p_version?: number };
        Returns: Json;
      };
      references_remove: { Args: { p_ids: string[]; p_reason?: string }; Returns: Json };
      reminders_remove: { Args: { p_ids: string[]; p_reason?: string }; Returns: Json };
      restore: { Args: { p_entity: string; p_id: string; p_reason?: string }; Returns: Json };
      restore_ticketed: {
        Args: { p_entity: string; p_id: string; p_reason?: string; p_ticket: string };
        Returns: Json;
      };
      role_save: {
        Args: {
          p_id: string;
          p_key: string;
          p_name_ar?: string;
          p_name_en: string;
          p_reason?: string;
          p_sort?: number;
          p_version?: number;
        };
        Returns: Json;
      };
      search: { Args: { p_limit?: number; p_q: string }; Returns: Json };
      setting_clear: { Args: { p_department: string; p_key: string; p_reason: string }; Returns: Json };
      setting_preview: {
        Args: { p_department: string; p_key: string; p_valid_from?: string; p_value: Json };
        Returns: Json;
      };
      setting_set: {
        Args: { p_department: string; p_key: string; p_reason?: string; p_valid_from?: string; p_value: Json };
        Returns: Json;
      };
      settings: { Args: { p_group: string }; Returns: Json };
      settings_log: { Args: { p_before?: string; p_limit?: number }; Returns: Json };
      side_field_save: { Args: { p_id: string; p_reason?: string; p_values: Json; p_version?: number }; Returns: Json };
      sign_in_check: { Args: { p_email: string; p_user_agent?: string }; Returns: string };
      sign_in_complete: {
        Args: { p_device_label?: string; p_provider?: string; p_user_agent?: string };
        Returns: string;
      };
      sign_in_event: {
        Args: { p_detail?: string; p_email: string; p_provider?: string; p_result: string; p_user_agent?: string };
        Returns: undefined;
      };
      sign_in_limited: { Args: { p_email: string }; Returns: string };
      sign_in_log: { Args: { p_before?: string; p_limit?: number; p_person?: string }; Returns: Json };
      sign_in_methods: { Args: Record<PropertyKey, never>; Returns: Json };
      sign_in_password_check: { Args: { p_email: string; p_user_agent?: string }; Returns: string };
      sign_in_password_refused: { Args: { p_detail: string; p_email: string; p_user_agent?: string }; Returns: string };
      task: { Args: { p_id: string }; Returns: Json };
      task_add_meeting: {
        Args: { p_body: string; p_happened_on: string; p_items?: Json; p_mentions?: string[]; p_task: string };
        Returns: Json;
      };
      task_contacts_set: { Args: { p_contacts: string[]; p_task: string }; Returns: Json };
      task_create: { Args: { p_mentions?: string[]; p_values: Json }; Returns: Json };
      task_helpers_set: { Args: { p_id: string; p_people: string[] }; Returns: Json };
      task_ref_add: { Args: { p_system: string; p_task: string; p_value: string }; Returns: Json };
      task_refs_remove: { Args: { p_ids: string[]; p_reason?: string }; Returns: Json };
      task_status_set: {
        Args: { p_close_items?: boolean; p_happened_on?: string; p_id: string; p_reason?: string; p_status: string };
        Returns: Json;
      };
      task_update: { Args: { p_id: string; p_values: Json; p_version: number }; Returns: Json };
      tasks: { Args: { p_filter?: Json; p_limit?: number; p_offset?: number }; Returns: Json };
      tasks_assign: { Args: { p_ids: string[]; p_owner: string; p_reason?: string }; Returns: Json };
      tasks_remove: { Args: { p_ids: string[]; p_reason?: string }; Returns: Json };
      team_load: { Args: { p_people?: string[] }; Returns: Json };
      team_retire: { Args: { p_id: string; p_move_to: string; p_reason: string }; Returns: Json };
      team_save: {
        Args: {
          p_code: string;
          p_department: string;
          p_id: string;
          p_lead?: string;
          p_name_ar?: string;
          p_name_en: string;
          p_reason?: string;
          p_version?: number;
        };
        Returns: Json;
      };
      undo: { Args: { p_request: string }; Returns: Json };
      undo_ticketed: { Args: { p_request: string; p_ticket: string }; Returns: Json };
      view_default_set: { Args: { p_page: string; p_view: string }; Returns: string };
      view_save: {
        Args: {
          p_id: string;
          p_name: string;
          p_page: string;
          p_query: Json;
          p_shared?: boolean;
          p_sort?: number;
          p_version?: number;
        };
        Returns: Json;
      };
      views: { Args: { p_page: string }; Returns: Json };
      views_remove: { Args: { p_ids: string[]; p_reason?: string }; Returns: Json };
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};

type DatabaseWithoutInternals = Omit<Database, '__InternalSupabase'>;

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, 'public'>];

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    keyof (DefaultSchema['Tables'] & DefaultSchema['Views']) | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Views'])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Views'])[TableName] extends {
      Row: infer R;
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema['Tables'] & DefaultSchema['Views'])
    ? (DefaultSchema['Tables'] & DefaultSchema['Views'])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R;
      }
      ? R
      : never
    : never;

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables'] | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables']
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'][TableName] extends {
      Insert: infer I;
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables']
    ? DefaultSchema['Tables'][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I;
      }
      ? I
      : never
    : never;

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables'] | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables']
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'][TableName] extends {
      Update: infer U;
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables']
    ? DefaultSchema['Tables'][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U;
      }
      ? U
      : never
    : never;

export type Enums<
  DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema['Enums'] | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions['schema']]['Enums']
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions['schema']]['Enums'][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema['Enums']
    ? DefaultSchema['Enums'][DefaultSchemaEnumNameOrOptions]
    : never;

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    keyof DefaultSchema['CompositeTypes'] | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions['schema']]['CompositeTypes']
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions['schema']]['CompositeTypes'][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema['CompositeTypes']
    ? DefaultSchema['CompositeTypes'][PublicCompositeTypeNameOrOptions]
    : never;

export const Constants = {
  api: {
    Enums: {},
  },
} as const;
