// `pnpm registry:sync` (TECH-SPEC §2.3, V123): the module registry → the database.
//
//   pnpm registry:sync            when the registry differs from supabase/registry.json: write a new migration that
//                                 makes the database agree, and the new registry.json
//   pnpm registry:sync --check    fail when they differ (a module.ts changed without syncing)
//
// The migration is idempotent and forward-only: pages, capabilities and setting definitions become the registry's
// (a page taken out is made inactive, never deleted); the five roles, each role's starting levels and capabilities,
// and each setting's default (a dated company-wide row, §3.2) are written only where none exist yet — so what an admin
// has changed in the browser is never overwritten by a later sync. REG-01 checks a database built from zero against
// registry.json.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import * as prettier from 'prettier';
import { modules } from '../../src/core/registry/index';
import { snapshotOf, type Snapshot } from '../../src/core/registry/snapshot';

const V2 = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');
const SNAPSHOT = path.join(V2, 'supabase', 'registry.json');
const MIGRATIONS = path.join(V2, 'supabase', 'migrations');

const text = (s: string | null) => (s === null ? 'null' : `'${s.replace(/'/g, "''")}'`);
const json = (v: unknown) => `${text(JSON.stringify(v))}::jsonb`;
const num = (n: number | null) => (n === null ? 'null' : String(n));
const list = (xs: string[]) => xs.map(text).join(', ');

/** registry.json as Prettier would leave it, so `pnpm format` never makes it differ. */
async function serialise(s: Snapshot): Promise<string> {
  const config = (await prettier.resolveConfig(SNAPSHOT)) ?? {};
  return prettier.format(JSON.stringify(s), { ...config, filepath: SNAPSHOT });
}

/** The next migration stamp: now (UTC), or one minute after the newest migration when that is later (V103). */
function nextStamp(): string {
  const newest = fs
    .readdirSync(MIGRATIONS)
    .filter((f) => /^\d{14}_/.test(f))
    .sort()
    .pop();
  const parse = (st: string) =>
    Date.UTC(
      +st.slice(0, 4),
      +st.slice(4, 6) - 1,
      +st.slice(6, 8),
      +st.slice(8, 10),
      +st.slice(10, 12),
      +st.slice(12, 14),
    );
  const after = newest ? parse(newest.slice(0, 14)) + 60_000 : 0;
  const t = new Date(Math.max(Date.now(), after));
  const p = (n: number, w = 2) => String(n).padStart(w, '0');
  return `${p(t.getUTCFullYear(), 4)}${p(t.getUTCMonth() + 1)}${p(t.getUTCDate())}${p(t.getUTCHours())}${p(t.getUTCMinutes())}${p(t.getUTCSeconds())}`;
}

function migrationOf(s: Snapshot): string {
  const out: string[] = [];
  out.push(
    '-- Generated by `pnpm registry:sync` from the module registry (src/modules/*/module.ts — TECH-SPEC §2.3, V123).',
    '-- Do not edit: change a module.ts and sync again. Pages, capabilities and setting definitions become the',
    "-- registry's; roles, their starting levels and capabilities, and setting defaults are written only where none",
    '-- exist, so what an admin has changed in the browser stays. Forward-only (V103).',
    '',
    "select audit.begin('system', 'registry.synced');",
    '',
    '-- the five roles (seeded once; renamed in the browser)',
    'insert into core.role (key, name_en, name_ar, sort, is_admin) values',
    s.roles
      .map((r) => `  (${text(r.key)}, ${text(r.name_en)}, ${text(r.name_ar)}, ${r.sort}, ${r.is_admin})`)
      .join(',\n'),
    'on conflict (key) do nothing;',
    '',
    '-- pages',
    'insert into core.page (key, module, route, nav_group, nav_order, levels_allowed, active) values',
    s.pages
      .map(
        (p) =>
          `  (${text(p.key)}, ${text(p.module)}, ${text(p.route)}, ${text(p.nav_group)}, ${num(p.nav_order)}, ` +
          `'{${p.levels.join(',')}}'::core.level[], true)`,
      )
      .join(',\n'),
    'on conflict (key) do update set module = excluded.module, route = excluded.route, nav_group = excluded.nav_group,',
    '  nav_order = excluded.nav_order, levels_allowed = excluded.levels_allowed, active = true;',
    `update core.page set active = false where active and key not in (${list(s.pages.map((p) => p.key))});`,
    '',
    '-- capabilities',
  );
  if (s.capabilities.length)
    out.push(
      'insert into core.capability (key, page_key, active) values',
      s.capabilities.map((c) => `  (${text(c.key)}, ${text(c.page)}, true)`).join(',\n'),
      'on conflict (key) do update set page_key = excluded.page_key, active = true;',
      `update core.capability set active = false where active and key not in (${list(s.capabilities.map((c) => c.key))});`,
    );
  else out.push('update core.capability set active = false where active;');
  out.push('', '-- setting definitions');
  if (s.settings.length)
    out.push(
      'insert into core.setting_def (key, group_page, schema, default_value, effective_dated, label_key, active) values',
      s.settings
        .map(
          (x) =>
            `  (${text(x.key)}, ${text(x.group)}, ${json(x.schema)}, ${json(x.default)}, ${x.effective_dated}, ` +
            `${text(x.label)}, true)`,
        )
        .join(',\n'),
      'on conflict (key) do update set group_page = excluded.group_page, schema = excluded.schema,',
      '  default_value = excluded.default_value, effective_dated = excluded.effective_dated,',
      '  label_key = excluded.label_key, active = true;',
      `update core.setting_def set active = false where active and key not in (${list(s.settings.map((x) => x.key))});`,
    );
  else out.push('update core.setting_def set active = false where active;');
  out.push('', '-- entities: the tables whose records are logged, undone and followed (V127)');
  if (s.entities.length)
    out.push(
      'insert into core.entity (key, table_name, page_key, owners, is_list, private, visible, level, history, active) values',
      s.entities
        .map(
          (e) =>
            `  (${text(e.key)}, ${text(e.table)}, ${text(e.page)}, ${text(e.owners)}, ${e.list}, ${e.private}, ${text(e.visible)}, ` +
            `${text(e.level)}, ${e.history}, true)`,
        )
        .join(',\n'),
      'on conflict (key) do update set table_name = excluded.table_name, page_key = excluded.page_key,',
      '  owners = excluded.owners, is_list = excluded.is_list, private = excluded.private, visible = excluded.visible,',
      '  level = excluded.level, history = excluded.history, active = true;',
      `update core.entity set active = false where active and key not in (${list(s.entities.map((e) => e.key))});`,
    );
  else out.push('update core.entity set active = false where active;');
  out.push(
    '',
    "-- each role's starting level on each page, where it has none",
    'insert into core.role_page_level (role_id, page_key, level)',
    'select r.id, v.page_key, v.level::core.level',
    'from (values',
    s.role_levels.map((x) => `  (${text(x.role)}, ${text(x.page)}, ${text(x.level)})`).join(',\n'),
    ') v (role_key, page_key, level)',
    'join core.role r on r.key = v.role_key',
    'where not exists (select 1 from core.role_page_level x',
    '                  where x.role_id = r.id and x.page_key = v.page_key and x.deleted_at is null);',
  );
  if (s.role_capabilities.length)
    out.push(
      '',
      "-- each role's starting capabilities, where it has none",
      'insert into core.role_capability (role_id, capability_key, granted)',
      'select r.id, v.capability_key, v.granted',
      'from (values',
      s.role_capabilities.map((x) => `  (${text(x.role)}, ${text(x.capability)}, ${x.granted})`).join(',\n'),
      ') v (role_key, capability_key, granted)',
      'join core.role r on r.key = v.role_key',
      'where not exists (select 1 from core.role_capability x',
      '                  where x.role_id = r.id and x.capability_key = v.capability_key and x.deleted_at is null);',
    );
  if (s.settings.length)
    out.push(
      '',
      "-- each setting's default (§3.2, V97, V155, V161): a new setting's, written once as a company-wide row from the",
      "-- floor date; a changed one, from today where no admin value is in force — never over an admin's",
      `select core.setting_defaults_sync(${json(s.settings.map((x) => ({ key: x.key, value: x.default })))});`,
    );
  out.push('', 'select audit.end();', '');
  return out.join('\n');
}

const check = process.argv.includes('--check');
const snapshot = snapshotOf(modules);
const before = fs.existsSync(SNAPSHOT) ? (JSON.parse(fs.readFileSync(SNAPSHOT, 'utf8')) as unknown) : null;

if (JSON.stringify(before) === JSON.stringify(snapshot)) {
  console.log('the registry and the database agree (supabase/registry.json) — nothing to sync');
  process.exit(0);
}
if (check) {
  console.error(
    'the registry changed and was not synced — run `pnpm registry:sync` and commit the migration it writes',
  );
  process.exit(1);
}
const stamp = nextStamp();
const file = path.join(MIGRATIONS, `${stamp}_core_registry_sync.sql`);
fs.writeFileSync(file, migrationOf(snapshot));
fs.writeFileSync(SNAPSHOT, await serialise(snapshot));
console.log(`wrote ${path.relative(V2, file)} and supabase/registry.json`);
